name: LICENSE CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  check_license:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: run license check
      run: |
        make license-check
