name: LICENSE CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  check-license:

    runs-on: ubuntu-latest

    steps:

    - name: run license check
      run: |
        make license-check
